# Generated by Django 5.2.12 on 2026-03-18 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.DateField()),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='planes.plane')),
            ],
        ),
    ]
